export interface OfficialModelSource {
  id: string;
  providerSlug: string;
  providerName: string;
  region: "cn" | "global";
  urls: string[];
  confidence: number;
  defaultStatus?: "active" | "preview" | "beta" | "deprecated" | "unknown";
  baselineCandidates?: Array<{
    slug: string;
    name: string;
    lifecycle_tier?: "current_frontier" | "current_mainstream" | "previous_generation" | "legacy" | "deprecated" | "unknown";
    model_status?: "active" | "preview" | "beta" | "deprecated" | "retired" | "unknown";
    source_url?: string;
  }>;
}

export const OFFICIAL_MODEL_SOURCES: OfficialModelSource[] = [
  {
    id: "official-openai",
    providerSlug: "openai",
    providerName: "OpenAI",
    region: "global",
    confidence: 0.95,
    urls: [
      "https://developers.openai.com/api/docs/models",
      "https://developers.openai.com/api/docs/pricing",
      "https://openai.com/api/pricing/",
    ],
  },
  {
    id: "official-anthropic",
    providerSlug: "anthropic",
    providerName: "Anthropic",
    region: "global",
    confidence: 0.95,
    urls: [
      "https://docs.anthropic.com/en/docs/about-claude/models",
      "https://docs.anthropic.com/en/docs/about-claude/pricing",
      "https://docs.anthropic.com/en/docs/about-claude/model-deprecations",
      "https://docs.anthropic.com/en/api/models-list",
      "https://www.anthropic.com/news",
    ],
    baselineCandidates: [
      { slug: "claude-fable-5", name: "Claude Fable 5", lifecycle_tier: "current_mainstream" },
      { slug: "claude-sonnet-4.5", name: "Claude Sonnet 4.5", lifecycle_tier: "current_mainstream" },
      { slug: "claude-opus-4.1", name: "Claude Opus 4.1", lifecycle_tier: "current_mainstream" },
      { slug: "claude-haiku-4.5", name: "Claude Haiku 4.5", lifecycle_tier: "current_mainstream" },
      { slug: "claude-3-7-sonnet-20250219", name: "claude-3-7-sonnet-20250219", lifecycle_tier: "previous_generation", model_status: "deprecated" },
    ],
  },
  {
    id: "official-google-gemini",
    providerSlug: "google",
    providerName: "Google Gemini",
    region: "global",
    confidence: 0.95,
    urls: [
      "https://ai.google.dev/gemini-api/docs/models",
      "https://ai.google.dev/gemini-api/docs/models?hl=en",
      "https://ai.google.dev/api/models",
      "https://ai.google.dev/gemini-api/docs/pricing",
      "https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models",
    ],
    baselineCandidates: [
      { slug: "gemini-3-pro", name: "Gemini 3 Pro", lifecycle_tier: "current_mainstream" },
      { slug: "gemini-3-flash", name: "Gemini 3 Flash", lifecycle_tier: "current_mainstream" },
      { slug: "gemini-3.5-flash", name: "Gemini 3.5 Flash", lifecycle_tier: "current_mainstream" },
      { slug: "gemini-3.1-pro", name: "Gemini 3.1 Pro", lifecycle_tier: "current_mainstream" },
      { slug: "gemini-3.1-flash", name: "Gemini 3.1 Flash", lifecycle_tier: "current_mainstream" },
      { slug: "gemini-2.5-pro", name: "Gemini 2.5 Pro", lifecycle_tier: "previous_generation" },
      { slug: "gemini-2.5-flash", name: "Gemini 2.5 Flash", lifecycle_tier: "previous_generation" },
      { slug: "veo-3.1", name: "Veo 3.1", lifecycle_tier: "current_mainstream" },
      { slug: "veo-3.1-fast", name: "Veo 3.1 Fast", lifecycle_tier: "current_mainstream" },
    ],
  },
  {
    id: "official-xai",
    providerSlug: "xai",
    providerName: "xAI",
    region: "global",
    confidence: 0.95,
    urls: ["https://docs.x.ai/developers/models", "https://docs.x.ai/developers/pricing", "https://docs.x.ai/developers/rest-api-reference/inference/models"],
    baselineCandidates: [
      { slug: "grok-4.3-latest", name: "grok-4.3-latest", lifecycle_tier: "current_frontier" },
      { slug: "grok-4.3", name: "grok-4.3", lifecycle_tier: "current_mainstream" },
      { slug: "grok-4-latest", name: "grok-4-latest", lifecycle_tier: "current_frontier" },
      { slug: "grok-4", name: "grok-4", lifecycle_tier: "current_mainstream" },
      { slug: "grok-3", name: "Grok 3", lifecycle_tier: "previous_generation" },
      { slug: "grok-imagine-video-1.5-preview", name: "grok-imagine-video-1.5-preview", lifecycle_tier: "current_mainstream", model_status: "preview" },
    ],
  },
  {
    id: "official-mistral",
    providerSlug: "mistral",
    providerName: "Mistral AI",
    region: "global",
    confidence: 0.9,
    urls: ["https://docs.mistral.ai/models/overview", "https://docs.mistral.ai/models/model-selection-guide", "https://docs.mistral.ai/api/endpoint/models", "https://mistral.ai/pricing"],
    baselineCandidates: [
      { slug: "mistral-large-3", name: "Mistral Large 3", lifecycle_tier: "current_frontier" },
      { slug: "mistral-large-latest", name: "mistral-large-latest", lifecycle_tier: "current_frontier" },
      { slug: "mistral-medium-3.5", name: "Mistral Medium 3.5", lifecycle_tier: "current_mainstream" },
      { slug: "mistral-medium-latest", name: "mistral-medium-latest", lifecycle_tier: "current_mainstream" },
      { slug: "mistral-small-4", name: "Mistral Small 4", lifecycle_tier: "current_mainstream" },
      { slug: "mistral-small-latest", name: "mistral-small-latest", lifecycle_tier: "current_mainstream" },
      { slug: "magistral-medium-latest", name: "magistral-medium-latest", lifecycle_tier: "current_mainstream" },
      { slug: "magistral-small-latest", name: "magistral-small-latest", lifecycle_tier: "current_mainstream" },
      { slug: "codestral-latest", name: "codestral-latest", lifecycle_tier: "current_mainstream" },
    ],
  },
  {
    id: "official-cohere",
    providerSlug: "cohere",
    providerName: "Cohere",
    region: "global",
    confidence: 0.9,
    urls: ["https://docs.cohere.com/docs/models", "https://cohere.com/pricing"],
  },
  {
    id: "official-perplexity",
    providerSlug: "perplexity",
    providerName: "Perplexity",
    region: "global",
    confidence: 0.9,
    urls: [
      "https://docs.perplexity.ai/docs/sonar/models",
      "https://docs.perplexity.ai/docs/sonar/models/sonar",
      "https://docs.perplexity.ai/docs/sonar/models/sonar-pro",
      "https://docs.perplexity.ai/docs/sonar/models/sonar-deep-research",
      "https://docs.perplexity.ai/docs/getting-started/pricing",
    ],
    baselineCandidates: [
      { slug: "sonar", name: "Sonar", lifecycle_tier: "current_mainstream" },
      { slug: "sonar-pro", name: "Sonar Pro", lifecycle_tier: "current_mainstream" },
      { slug: "sonar-reasoning-pro", name: "Sonar Reasoning Pro", lifecycle_tier: "current_mainstream" },
      { slug: "sonar-deep-research", name: "Sonar Deep Research", lifecycle_tier: "current_mainstream" },
      { slug: "pplx-embed-v1-4b", name: "pplx-embed-v1-4b", lifecycle_tier: "current_mainstream" },
    ],
  },
  {
    id: "official-together",
    providerSlug: "together",
    providerName: "Together AI",
    region: "global",
    confidence: 0.85,
    urls: ["https://docs.together.ai/docs/serverless-models", "https://www.together.ai/pricing"],
  },
  {
    id: "official-fireworks",
    providerSlug: "fireworks",
    providerName: "Fireworks AI",
    region: "global",
    confidence: 0.85,
    urls: ["https://docs.fireworks.ai/models", "https://fireworks.ai/pricing"],
  },
  {
    id: "official-groq",
    providerSlug: "groq",
    providerName: "Groq",
    region: "global",
    confidence: 0.85,
    urls: ["https://console.groq.com/docs/models", "https://groq.com/pricing/"],
  },
  {
    id: "official-meta-llama",
    providerSlug: "meta",
    providerName: "Meta Llama",
    region: "global",
    confidence: 0.85,
    urls: [
      "https://www.llama.com/models/llama-4/",
      "https://www.llama.com/docs/model-cards-and-prompt-formats/llama4/",
      "https://raw.githubusercontent.com/meta-llama/llama-models/main/models/llama4/MODEL_CARD.md",
      "https://raw.githubusercontent.com/meta-llama/llama-models/main/models/llama3_3/MODEL_CARD.md",
      "https://raw.githubusercontent.com/meta-llama/llama-models/main/models/llama3_2/MODEL_CARD.md",
    ],
    baselineCandidates: [
      { slug: "llama-4-scout", name: "Llama 4 Scout", lifecycle_tier: "current_mainstream" },
      { slug: "llama-4-maverick", name: "Llama 4 Maverick", lifecycle_tier: "current_mainstream" },
      { slug: "llama-4-behemoth", name: "Llama 4 Behemoth", lifecycle_tier: "current_frontier" },
    ],
  },
  {
    id: "official-deepseek",
    providerSlug: "deepseek",
    providerName: "DeepSeek",
    region: "cn",
    confidence: 0.95,
    urls: ["https://api-docs.deepseek.com/quick_start/pricing", "https://api-docs.deepseek.com/news/"],
  },
  {
    id: "official-aliyun-bailian",
    providerSlug: "aliyun-bailian",
    providerName: "阿里云百炼 / 通义千问",
    region: "cn",
    confidence: 0.9,
    urls: ["https://help.aliyun.com/zh/model-studio/models", "https://help.aliyun.com/zh/model-studio/model-pricing", "https://help.aliyun.com/zh/model-studio/release-notes"],
  },
  {
    id: "official-volcengine",
    providerSlug: "volcengine",
    providerName: "火山方舟 / 豆包",
    region: "cn",
    confidence: 0.9,
    urls: ["https://www.volcengine.com/docs/82379/1099455", "https://www.volcengine.com/docs/82379/1099320"],
  },
  {
    id: "official-tencent-hunyuan",
    providerSlug: "tencent-hunyuan",
    providerName: "腾讯混元",
    region: "cn",
    confidence: 0.9,
    urls: ["https://cloud.tencent.com/document/product/1729/101854", "https://cloud.tencent.com/document/product/1729"],
  },
  {
    id: "official-baidu-qianfan",
    providerSlug: "baidu-qianfan",
    providerName: "百度千帆 / 文心",
    region: "cn",
    confidence: 0.9,
    urls: ["https://cloud.baidu.com/doc/WENXINWORKSHOP/s/hlrk4akp7", "https://cloud.baidu.com/doc/WENXINWORKSHOP/index.html"],
  },
  {
    id: "official-zhipu",
    providerSlug: "zhipu",
    providerName: "智谱 GLM",
    region: "cn",
    confidence: 0.9,
    urls: ["https://open.bigmodel.cn/dev/api/normal-model/glm-4", "https://open.bigmodel.cn/pricing"],
  },
  {
    id: "official-moonshot",
    providerSlug: "moonshot",
    providerName: "月之暗面 Kimi",
    region: "cn",
    confidence: 0.9,
    urls: ["https://platform.moonshot.cn/docs/pricing", "https://platform.moonshot.cn/docs"],
  },
  {
    id: "official-minimax",
    providerSlug: "MiniMax",
    providerName: "MiniMax",
    region: "cn",
    confidence: 0.85,
    urls: ["https://platform.minimaxi.com/document/Price", "https://platform.minimaxi.com/document"],
  },
  {
    id: "official-siliconflow",
    providerSlug: "siliconflow",
    providerName: "硅基流动",
    region: "cn",
    confidence: 0.85,
    urls: ["https://docs.siliconflow.cn/cn/api-reference/chat-completions/chat-completions", "https://siliconflow.cn/pricing"],
  },
  {
    id: "official-modelscope",
    providerSlug: "modelscope",
    providerName: "ModelScope 魔搭",
    region: "cn",
    confidence: 0.8,
    urls: ["https://modelscope.cn/models"],
  },
];
