export interface OfficialModelSource {
  id: string;
  providerSlug: string;
  providerName: string;
  region: "cn" | "global";
  urls: string[];
  confidence: number;
  defaultStatus?: "active" | "preview" | "beta" | "deprecated" | "unknown";
}

export const OFFICIAL_MODEL_SOURCES: OfficialModelSource[] = [
  {
    id: "official-openai",
    providerSlug: "openai",
    providerName: "OpenAI",
    region: "global",
    confidence: 0.95,
    urls: [
      "https://developers.openai.com/api/docs/models",
      "https://developers.openai.com/api/docs/pricing",
      "https://openai.com/api/pricing/",
    ],
  },
  {
    id: "official-anthropic",
    providerSlug: "anthropic",
    providerName: "Anthropic",
    region: "global",
    confidence: 0.95,
    urls: [
      "https://platform.claude.com/docs/en/about-claude/models/overview",
      "https://platform.claude.com/docs/en/about-claude/model-deprecations",
      "https://www.anthropic.com/news",
    ],
  },
  {
    id: "official-google-gemini",
    providerSlug: "google",
    providerName: "Google Gemini",
    region: "global",
    confidence: 0.95,
    urls: [
      "https://ai.google.dev/gemini-api/docs/models",
      "https://ai.google.dev/gemini-api/docs/pricing",
    ],
  },
  {
    id: "official-xai",
    providerSlug: "xai",
    providerName: "xAI",
    region: "global",
    confidence: 0.95,
    urls: ["https://docs.x.ai/developers/models", "https://x.ai/api"],
  },
  {
    id: "official-mistral",
    providerSlug: "mistral",
    providerName: "Mistral AI",
    region: "global",
    confidence: 0.9,
    urls: ["https://docs.mistral.ai/getting-started/models/models_overview/", "https://mistral.ai/pricing"],
  },
  {
    id: "official-cohere",
    providerSlug: "cohere",
    providerName: "Cohere",
    region: "global",
    confidence: 0.9,
    urls: ["https://docs.cohere.com/docs/models", "https://cohere.com/pricing"],
  },
  {
    id: "official-perplexity",
    providerSlug: "perplexity",
    providerName: "Perplexity",
    region: "global",
    confidence: 0.9,
    urls: ["https://docs.perplexity.ai/models/model-cards", "https://docs.perplexity.ai/guides/pricing"],
  },
  {
    id: "official-together",
    providerSlug: "together",
    providerName: "Together AI",
    region: "global",
    confidence: 0.85,
    urls: ["https://docs.together.ai/docs/serverless-models", "https://www.together.ai/pricing"],
  },
  {
    id: "official-fireworks",
    providerSlug: "fireworks",
    providerName: "Fireworks AI",
    region: "global",
    confidence: 0.85,
    urls: ["https://docs.fireworks.ai/models", "https://fireworks.ai/pricing"],
  },
  {
    id: "official-groq",
    providerSlug: "groq",
    providerName: "Groq",
    region: "global",
    confidence: 0.85,
    urls: ["https://console.groq.com/docs/models", "https://groq.com/pricing/"],
  },
  {
    id: "official-meta-llama",
    providerSlug: "meta",
    providerName: "Meta Llama",
    region: "global",
    confidence: 0.85,
    urls: ["https://www.llama.com/models/", "https://ai.meta.com/llama/"],
  },
  {
    id: "official-deepseek",
    providerSlug: "deepseek",
    providerName: "DeepSeek",
    region: "cn",
    confidence: 0.95,
    urls: ["https://api-docs.deepseek.com/quick_start/pricing", "https://api-docs.deepseek.com/news/"],
  },
  {
    id: "official-aliyun-bailian",
    providerSlug: "aliyun-bailian",
    providerName: "阿里云百炼 / 通义千问",
    region: "cn",
    confidence: 0.9,
    urls: ["https://help.aliyun.com/zh/model-studio/models", "https://help.aliyun.com/zh/model-studio/model-pricing", "https://help.aliyun.com/zh/model-studio/release-notes"],
  },
  {
    id: "official-volcengine",
    providerSlug: "volcengine",
    providerName: "火山方舟 / 豆包",
    region: "cn",
    confidence: 0.9,
    urls: ["https://www.volcengine.com/docs/82379/1099455", "https://www.volcengine.com/docs/82379/1099320"],
  },
  {
    id: "official-tencent-hunyuan",
    providerSlug: "tencent-hunyuan",
    providerName: "腾讯混元",
    region: "cn",
    confidence: 0.9,
    urls: ["https://cloud.tencent.com/document/product/1729/101854", "https://cloud.tencent.com/document/product/1729"],
  },
  {
    id: "official-baidu-qianfan",
    providerSlug: "baidu-qianfan",
    providerName: "百度千帆 / 文心",
    region: "cn",
    confidence: 0.9,
    urls: ["https://cloud.baidu.com/doc/WENXINWORKSHOP/s/hlrk4akp7", "https://cloud.baidu.com/doc/WENXINWORKSHOP/index.html"],
  },
  {
    id: "official-zhipu",
    providerSlug: "zhipu",
    providerName: "智谱 GLM",
    region: "cn",
    confidence: 0.9,
    urls: ["https://open.bigmodel.cn/dev/api/normal-model/glm-4", "https://open.bigmodel.cn/pricing"],
  },
  {
    id: "official-moonshot",
    providerSlug: "moonshot",
    providerName: "月之暗面 Kimi",
    region: "cn",
    confidence: 0.9,
    urls: ["https://platform.moonshot.cn/docs/pricing", "https://platform.moonshot.cn/docs"],
  },
  {
    id: "official-minimax",
    providerSlug: "MiniMax",
    providerName: "MiniMax",
    region: "cn",
    confidence: 0.85,
    urls: ["https://platform.minimaxi.com/document/Price", "https://platform.minimaxi.com/document"],
  },
  {
    id: "official-siliconflow",
    providerSlug: "siliconflow",
    providerName: "硅基流动",
    region: "cn",
    confidence: 0.85,
    urls: ["https://docs.siliconflow.cn/cn/api-reference/chat-completions/chat-completions", "https://siliconflow.cn/pricing"],
  },
  {
    id: "official-modelscope",
    providerSlug: "modelscope",
    providerName: "ModelScope 魔搭",
    region: "cn",
    confidence: 0.8,
    urls: ["https://modelscope.cn/models"],
  },
];
